fix branch name

diff --git a/.github/workflows/build-test-ci.yaml b/.github/workflows/build-test-ci.yaml
--- a/.github/workflows/build-test-ci.yaml
+++ b/.github/workflows/build-test-ci.yaml
@@ -4,7 +4,7 @@ on:
   push:
     branches: [ "build-test-ci" ]
   pull_request:
-    branches: [ "master" ]
+    branches: [ "main" ]
     types: [ closed ]
   workflow_dispatch:
 
@@ -43,7 +43,13 @@ jobs:
         docker run -it -v $(pwd)/configs/:/code/configs -e WANDB_API_KEY=${{ secrets.WANDB_API_KEY }} --name nlqs-tests -d nlqs/tests:0.1
 
     - name: Execute tests
-      run: docker exec nlqs-tests bash -c "conda run --no-capture-output -n py39 ./run_tests.sh openai_gpt4 all"
+      run: |
+        docker exec nlqs-tests bash -c "conda run --no-capture-output -n py39 ./run_tests.sh openai_gpt4 all"
+        status=$?
+        if [ $status -ne 0 ]; then
+          echo "test failed with status $status"
+          exit $status
+        fi
 
     - name: Cleanup
       run: docker rm -f nlqs-tests
